Refactoring service apis

diff --git a/.github/workflows/manual_deployment.yaml b/.github/workflows/manual_deployment.yaml
--- a/.github/workflows/manual_deployment.yaml
+++ b/.github/workflows/manual_deployment.yaml
@@ -17,95 +17,58 @@ on:
   
 jobs:
 
-  imports:
-    name: Imports
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: imports
-        token: ${{ secrets.DEPLOY_ACCESS }}
-
-  errcheck:
-    name: Errcheck
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: errcheck
-        token: ${{ secrets.DEPLOY_ACCESS }}
-
-  lint:
-    name: Lint
-    runs-on: ubuntu-latest
+  build:
+    name: Audit
+    runs-on: ubuntu-20.04
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v1
+        uses: actions/setup-go@v2
         with:
-          go-version: 1.16
+          go-version: 1.21
 
       - name: Check out code
-        uses: actions/checkout@v1
+        uses: actions/checkout@v2
 
-      - name: Lint Go Code
-        run: |
-          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
-          go get -u golang.org/x/lint/golint 
-          make lint
+      - name: Verify dependencies
+        run: go mod verify
 
-  shadow:
-    name: Shadow
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: shadow
-        token: ${{ secrets.DEPLOY_ACCESS }}
+      - name: Verify vendor
+        run: go mod vendor
 
-  staticcheck:
-    name: StaticCheck
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: staticcheck
-        token: ${{ secrets.DEPLOY_ACCESS }}
+      - name: Build
+        run: go build -v ./...
 
-  sec:
-    name: Sec
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: sec
-        token: ${{ secrets.DEPLOY_ACCESS }}
-        flags: "-exclude=G104"
+      - name: Run go vet
+        run: go vet ./...
+
+      - name: Install staticcheck
+        run: go install honnef.co/go/tools/cmd/staticcheck@latest
+
+      - name: Run staticcheck
+        run: staticcheck ./...
+
+      - name: Install golint
+        run: go install golang.org/x/lint/golint@latest
+
+      - name: Run golint
+        run: golint ./...
 
   test:
     name: Test
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        go: ["1.16"]
+        os: [ubuntu-20.04, macos-latest, windows-latest]
+        go: ["1.21"]
     runs-on: ${{ matrix.os }}
+    needs: [build]
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v1
+        uses: actions/setup-go@v2
         with:
-          go-version: 1.16
+          go-version: 1.21
 
       - name: Check out code
-        uses: actions/checkout@v1
+        uses: actions/checkout@v2
 
       - name: Vars
         id: vars
@@ -121,40 +84,16 @@ jobs:
           restore-keys: |
                         ${{ runner.os }}-go${{ matrix.go }}-release
 
-      - name: Run Unit tests.
-        run: make test-coverage
-      
-      - name: Upload Coverage report to CodeCov
-        uses: codecov/codecov-action@v1
-        with:
-          token: ${{secrets.DEPLOY_ACCESS}}
-          file: ./coverage.txt
+      - name: Verify vendor
+        run: go mod vendor
 
-      - name: Build and Test
-        run: make test
-
-      - name: Test Coverage
-        run: make test-coverage
-
-  build:
-    name: Build
-    runs-on: ubuntu-latest 
-    needs: [imports, errcheck, lint, shadow, staticcheck, sec, test]
-    steps:
-      - name: Set up Go
-        uses: actions/setup-go@v1
-        with:
-          go-version: 1.16
-
-      - name: Check out code
-        uses: actions/checkout@v1
-
-      - name: Build
-        run: make build
+      - name: Test
+        run: go test -race -vet=off ./...
 
   setup:
-    needs: [build]
-    runs-on: ubuntu-latest
+    name: Setup
+    needs: [test]
+    runs-on: ubuntu-20.04
     outputs:
       repo: ${{ steps.vars.outputs.repo }}
       commit: ${{ steps.vars.outputs.commit }}
@@ -188,8 +127,9 @@ jobs:
             ${{ github.workspace }}/go.sum
   
   docker:
+    name: Docker
     needs: [setup]
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     steps:
       - name: Download repository
         uses: actions/download-artifact@v2
@@ -210,8 +150,9 @@ jobs:
           build-args: COMMIT=${{ needs.setup.outputs.commit }}
   
   deploy:
+    name: Deploy
     needs: docker
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     steps:
       - name: Download repository
         uses: actions/download-artifact@v2
@@ -219,8 +160,8 @@ jobs:
           name: repository
       - name: Install kubectl
         run: |
-          curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
-          curl -LO "https://dl.k8s.io/v1.22.0/bin/linux/amd64/kubectl.sha256"
+          curl -LO https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
+          curl -LO "https://dl.k8s.io/v1.28.3/bin/linux/amd64/kubectl.sha256"
           echo "$(<kubectl.sha256) kubectl" | sha256sum --check
           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
           kubectl version --client
@@ -228,20 +169,86 @@ jobs:
         run: |
           mkdir -p $HOME/.kube/
           case ${{ github.event.inputs.env }} in
-                qa) echo "${{ secrets.KUBE_QA_URL }}" > $HOME/.kube/config ;;
-            stage) echo "${{ secrets.KUBE_STAGE_URL }}" > $HOME/.kube/config ;;
-              prod) echo "${{ secrets.KUBE_PROD_URL }}" > $HOME/.kube/config ;;
+                qa) echo "${{ secrets.QA_CLUSTER_CONFIG }}" > $HOME/.kube/config ;;
+            stage) echo "${{ secrets.STAGE_CLUSTER_CONFIG }}" > $HOME/.kube/config ;;
+              prod) echo "${{ secrets.PROD_CLUSTER_CONFIG }}" > $HOME/.kube/config ;;
                 *) echo "Invalid environment"; exit 1;;
           esac
+
           case ${{ github.event.inputs.env }} in
-                qa) echo "${{ secrets.KUBE_QA_CONFIG }}" > $HOME/.kube/qa.yaml ;;
-            stage) echo "${{ secrets.KUBE_STAGE_CONFIG }}" > $HOME/.kube/stage.yaml ;;
-              prod) echo "${{ secrets.KUBE_PROD_CONFIG }}" > $HOME/.kube/prod.yaml ;;
+                qa) echo "${{ secrets.QA_CLUSTER_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+            stage) echo "${{ secrets.STAGE_CLUSTER_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+              prod) echo "${{ secrets.PROD_CLUSTER_CLIENT_CERT }}" > $HOME/.kube/client.crt ;;
+                *) echo "Invalid environment"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.QA_CLUSTER_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+            stage) echo "${{ secrets.STAGE_CLUSTER_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+              prod) echo "${{ secrets.PROD_CLUSTER_CLIENT_KEY }}" > $HOME/.kube/client.key ;;
+                *) echo "Invalid environment"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo "${{ secrets.QA_CLUSTER_ENV }}" > $HOME/.kube/qa.properties ;;
+            stage) echo "${{ secrets.STAGE_CLUSTER_ENV }}" > $HOME/.kube/stage.properties ;;
+              prod) echo "${{ secrets.PROD_CLUSTER_ENV }}" > $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo DB_ROOT_CA=${{ secrets.QA_DB_ROOT_CA }} >> $HOME/.kube/qa.properties ;;
+            stage) echo DB_ROOT_CA=${{ secrets.STAGE_DB_ROOT_CA }} >> $HOME/.kube/stage.properties ;;
+              prod) DB_ROOT_CA=${{ secrets.PROD_DB_ROOT_CA }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo DB_SSL_CERT=${{ secrets.QA_DB_SSL_CERT }} >> $HOME/.kube/qa.properties ;;
+            stage) echo DB_SSL_CERT=${{ secrets.STAGE_DB_SSL_CERT }} >> $HOME/.kube/stage.properties ;;
+              prod) DB_SSL_CERT=${{ secrets.PROD_DB_SSL_CERT }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo DB_SSL_KEY=${{ secrets.QA_DB_SSL_KEY }} >> $HOME/.kube/qa.properties ;;
+            stage) echo DB_SSL_KEY=${{ secrets.STAGE_DB_SSL_KEY }} >> $HOME/.kube/stage.properties ;;
+              prod) DB_SSL_KEY=${{ secrets.PROD_DB_SSL_KEY }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo API_SSL_CERT=${{ secrets.QA_API_SSL_CERT }} >> $HOME/.kube/qa.properties ;;
+            stage) echo API_SSL_CERT=${{ secrets.STAGE_API_SSL_CERT }} >> $HOME/.kube/stage.properties ;;
+              prod) API_SSL_CERT=${{ secrets.PROD_API_SSL_CERT }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo API_SSL_KEY=${{ secrets.QA_API_SSL_KEY }} >> $HOME/.kube/qa.properties ;;
+            stage) echo API_SSL_KEY=${{ secrets.STAGE_API_SSL_KEY }} >> $HOME/.kube/stage.properties ;;
+              prod) API_SSL_KEY=${{ secrets.PROD_API_SSL_KEY }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo API_PRIVATE_KEY=${{ secrets.QA_API_PRIVATE_KEY }} >> $HOME/.kube/qa.properties ;;
+            stage) echo API_PRIVATE_KEY=${{ secrets.STAGE_API_PRIVATE_KEY }} >> $HOME/.kube/stage.properties ;;
+              prod) API_PRIVATE_KEY=${{ secrets.PROD_API_PRIVATE_KEY }} >> $HOME/.kube/prod.properties ;;
+                *) echo "Invalid config"; exit 1;;
+          esac
+
+          case ${{ github.event.inputs.env }} in
+                qa) echo API_PUBLIC_KEY=${{ secrets.QA_API_PUBLIC_KEY }} >> $HOME/.kube/qa.properties ;;
+            stage) echo API_PUBLIC_KEY=${{ secrets.STAGE_API_PUBLIC_KEY }} >> $HOME/.kube/stage.properties ;;
+              prod) API_PUBLIC_KEY=${{ secrets.PROD_API_PUBLIC_KEY }} >> $HOME/.kube/prod.properties ;;
                 *) echo "Invalid config"; exit 1;;
           esac
       - name: Deploy
         run: |
+          kubectl --kubeconfig $HOME/.kube/config delete configmap gf-user-db-config -n ${{ github.event.inputs.env }}
+          kubectl --kubeconfig $HOME/.kube/config create configmap gf-user-db-config -n ${{ github.event.inputs.env }} --from-file=deploy/k8s/${{ github.event.inputs.env }}/config/postgres/
           kubectl --kubeconfig $HOME/.kube/config delete secret -n ${{ github.event.inputs.env }} gf-user-secret
-          kubectl --kubeconfig $HOME/.kube/config create secret generic -n ${{ github.event.inputs.env }} gf-user-secret --from-env-file=$HOME/.kube/${{ github.event.inputs.env }}.yaml
+          kubectl --kubeconfig $HOME/.kube/config create secret generic -n ${{ github.event.inputs.env }} gf-user-secret --from-env-file=$HOME/.kube/${{ github.event.inputs.env }}.properties
           kubectl --kubeconfig $HOME/.kube/config apply -k deploy/k8s/${{ github.event.inputs.env }}
           kubectl --kubeconfig $HOME/.kube/config patch deployment gf-user-deployment --namespace=${{ github.event.inputs.env }} -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"rollout\":\"`date +'%s'`\"}}}}}"
